# Kubernetes module
[kubernetes]
format = '[$symbol$context( \($namespace\))]($style) '
disabled = false
symbol = "â˜¸ï¸ "
style = "dimmed green"

[kubernetes.context_aliases]
# Regex to match and alias context names
"dev-cluster.*" = "dev"
"test-cluster.*" = "test"
"prod-cluster.*" = "prod"

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bold dimmed green'

[os.symbols]
AlmaLinux = "ğŸ’  "
Alpine = "ğŸ”ï¸ "
Amazon = "ğŸ™‚ "
Arch = "ğŸ—ï¸ "
CentOS = "ğŸ’  "
Debian = "ğŸŒ€ "
Fedora = "ğŸ© "
FreeBSD = "ğŸ˜ˆ "
Gentoo = "ğŸ—œï¸ "
HardenedBSD = "ğŸ›¡ï¸ "
Illumos = "ğŸ¦ "
Kali = "ğŸ‰ "
Linux = "ğŸ§ "
Manjaro = "ğŸ¥­ "
Mariner = "ğŸŒŠ "
NetBSD = "ğŸš© "
OpenBSD = "ğŸ¡ "
openSUSE = "ğŸ¦ "
OracleLinux = "ğŸ¦´ "
Redhat = "ğŸ© "
RedHatEnterprise = "ğŸ© "
RockyLinux = "ğŸ’  "
SUSE = "ğŸ¦ "
Ubuntu = "ğŸ¯ "

[os]
format = "on [($name )]($style)"
style = "bold blue"
disabled = false
